version: '3'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${JAMRAILS_DATABASE_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jamrails_net

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: 'true'
      RAILS_LOG_TO_STDOUT: 'true'
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - jamrails_net
    restart: unless-stopped

networks:
  jamroulette_net:
    driver: bridge

volumes:
  postgres_data:
    driver: local
